apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controllers/
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-config
  namespace: flux-system
spec:
  dependsOn:
    - name: infrastructure-controllers
  interval: 10m0s
  path: ./infrastructure/config/homelab
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-controllers
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/controllers/metallb
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-config
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-controllers
  interval: 10m0s
  path: ./infrastructure/config/homelab/metallb
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-ingress-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: metallb-config
  interval: 10m0s
  path: ./infrastructure/controllers/nginx
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nginx-config
  namespace: flux-system
spec:
  dependsOn:
    - name: nginx-ingress-controllers
  interval: 10m0s
  path: ./infrastructure/config/homelab/nginx
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/config/homelab/cloudflared
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cloudflared-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: cloudflared-config
  interval: 10m0s
  path: ./infrastructure/controllers/cloudflared
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-config
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./infrastructure/config/homelab/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age

---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: monitoring-controllers
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring-config
    - name: nginx-config
  interval: 10m0s
  path: ./infrastructure/controllers/monitoring
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system