apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkding
  namespace: linkding
  labels:
    app: linkding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: linkding
  template:
    metadata:
      labels:
        app: linkding
    spec:
      containers:
      - name: linkding
        image: sissbruecker/linkding:latest
        ports:
        - containerPort: 9090
        env:
        - name: LD_SUPERUSER_NAME
          value: "admin"
        - name: LD_SUPERUSER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: linkding-secret
              key: password
        volumeMounts:
          - name: linkding
            mountPath: /etc/linkding/data # mounts the volume at /etc/linkding/data inside the container
      volumes:
        - name: linkding
          persistentVolumeClaim:
            claimName: linkding # this creates a volume for the PVC. The name matches the volumeMounts.name above.