apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding-ingress
  namespace: linkding    
spec:
  ingressClassName: nginx
  
  #tls:
  #- hosts:
  #    - linkding.danielmorgsilva.dev
  #  secretName: danielmorgsilva-dev-secret
  rules:
  - host: linkding.danielmorgsilva.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkding
            port:
              number: 9090