apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:333nrzSa,iv:OK87uSLlLSfrB8HRS93fYE87LV71Mw2UJH/eTOd01SQ=,tag:ZzLoOhvPfcdJH8in8RV4lg==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBrMmZCSGZtSTlvVWp5RnlN
            S2FOM0h5ZTNPaGZQZWRmclF1Ym8zNXRxekJNClcvbC9lK1lZTCtLa2xla2lFb05N
            K3JSWlc1Um02RGtIWWRsYUFObWYrOU0KLS0tIGc5bk9HNjZLUmNxdk93dlpnQUxQ
            VHZvbmtyTXM0dEh3WkppU0tnSCtXWlEKRYRvo1gKwcT3py5lgEXLjdi+gnqU+r/o
            y+M0ZN+tb3cs/dAS61kQu/pAt0dfLDTg8SBX/MFKNVQ1eeGj1oHunQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T20:15:57Z"
    mac: ENC[AES256_GCM,data:Ll/o9HxrgyGijE1HAiGLWY0Rbrhwmwq8+fi3qXpMCF4MHDQDVYTwEF5ARsMdG2Hx41/XYdN3qU3nhg+Uoq797et/a8RHz8hzSbsETgsGt1YYYUppkGQ9c5fA7V+8v/VzUtOiF6DeApkk4TvSEOeZyYKm4rGf9mrh76XO1UUCR3o=,iv:lI8xAJ0AmUqEe9fH1L5oLkaXNzRi8qNTrEVrfmiy6Qs=,tag:YMsW7m6VBAwfFYzHLEI4Dg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
