apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:aExtd2d1,iv:CiVZ+Bc0IRu60uKwJRdAXijiWrf0bqQ8Mm3H5tu9j0c=,tag:Czr1txjcwQNW7JcPS+sOxA==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3L3NHclg2akxJT3pkbTZj
            VHkwR0VBSncyZmpTZ2M0ejNyMFpDRzhqcTE0Cld1YVFjWFpFQzdxNEJ3Z3U2bmhV
            NHBHemxoU2hSamZXdmpqQUg0TUE0MTAKLS0tIEVkdTdJUVhDR05uU01ENVBFZmRP
            OUNXYnc0ekhIUXFVTE9SNzlUUWdQd0EKaGMy0SyVkDuUOB4UEVYo3PXmiZIMYjXq
            C3XSOrjOcosdpiZRaCvUPzQZSL59EicXe+SfVRTpvyu89ZXMya3VxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T14:46:11Z"
    mac: ENC[AES256_GCM,data:rnynkMKajFrC2+WVyP9HW9jrd0KONX7WhjCxWp3bxiITuIpoChqP1XbLoY+NTx1V73pPBKC5t6vXhMepDxTfA9PTM5sKR1gp/omfDzytoGVNGNBFTsIC05tEDc18whcuMdOIZHTDTeU6Usn3nM94fZwM6IB8tetS8D0IQ4zUTFQ=,iv:iM4kU9IJiFPcrznIsHUZm1vWvjkCUkmELuDdzeF/VjI=,tag:GHTwcjEIig8P/MkrB74Cew==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1