apiVersion: v1
kind: Secret
metadata:
    name: linkding-secret
    namespace: linkding
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:rEFfOedC,iv:IbOmpTGEE5bfYyJxO21LviIeLmHz64uEGrNkloYhgsM=,tag:jXezolUsLb8/uxEs8pqSOQ==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKdmYyenNrd1NBbUxRczRV
            a2FGQVFYTWlNS0M5QkU0TnRDZ0FIWUh0MEdNCmJuSEx3ZnpEbWFONW9SWEdwQnZJ
            L2p2OTIzam5HdytpYndnK0pRaXJVWFUKLS0tIDVmZDRKTGR1RW16YjhSVER5QW9W
            czZJQ0FWMUdKN0p6SXhLUCtsZFZhZVkKJC4BJRL30DvJktFnNkxcyXs4yvrJLrqt
            aq224Tm67c32/bjqJYM3lnx6ooMXe6oagXB4kMXblishgiiSwDTZsQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-24T16:23:44Z"
    mac: ENC[AES256_GCM,data:tXmov6b3eurbF6T4bWuzBfDnX1xYnnA3cBF+7YtajT2s+rQy40l9Dun6+445E9cWq7fvT77LC/nuZJUaQoP630x3Jj5DzwubvSbGUJ7RWxfZ2Iz6LXirPw+B9mf7BfQYSfIR6C2osb1oJ3RRAtkvysFsAJom4p105MSn0xLEfw4=,iv:+soaNF2HfNYiRI6eNAbu5ZtmNNMADNQuCQSCsTwkKFE=,tag:qpiMFtGXU+Z90WhzNyc79g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1