apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgresql-system
    labels:
        app: postgres
type: Opaque
stringData:
    POSTGRES_DB: ENC[AES256_GCM,data:YvzDnbI4gc7C,iv:96kNH0W7mn6Jdo8yJtro/yZSV9cgAi5N9yI/wfMBkqM=,tag:d8hVP37boPANZXHm0/d4UQ==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:P4QbzM9q4h3f,iv:uWNkJOv7URnhvMk8h9qnpwbUIlXTpHRpssyxF0dZqTI=,tag:bUXpwviIA5bwh1Y8FI2WeA==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:bhw6+vj4,iv:RoUyy/n/uCAmGdo7rjwr/8a0bWtAfGCbMyHSuEX2y+U=,tag:j+mpNtkuUvqrxxLzppj8kg==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxZnVhQTB6VW52WWFPbUwv
            ZFVlMkgvSzdad1FYU0RheXNENk9RYlNzNGt3CjNnbXZkMVl0WEtYUmlBak96ZktJ
            UkhhdFUyV3ZwcXpOSGhITzNiTDEzREEKLS0tIFFUZWxsUnZrZ29adHZ4azBzaFBp
            QW5nWlhPUkErTWlVamxzaHFQU1NtTlkKgYaJ530HZVtI4+FLfczOxqp/95LoFSq3
            1WzyItnO/r5IG4QS8pXakL5uR/PCj7uiJjWy7S9mEYVfLtQv1GaU4g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-24T15:19:48Z"
    mac: ENC[AES256_GCM,data:LrdXH6L7bnAhkAHMYuVDDPIFDjQGF7JukvV+2tEJp5r6aNncrtvg0ht9aeewlwJmaMXcaLmQXHz4f28uhY9hNk093+DhVlTrkawBsCVQTF+P2wQEIGhgJn3RTvv4mudYB+jN+K6kV2dMW1T4+3VcdaUEOE2v2S+GQJHArS89tRU=,iv:K+tEFTUiINV1jhfnoHvnM4FF+SEvZaqHGrjXun30QB0=,tag:nMAZ5GQ4ZjthaO4vJ3YOjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
