apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:5umd005lHhnVBS7/XppEKE0CkBq1zT+iRMtoSkMWDepNoXHMFSfo572tO2XvKSTt6ud5owhIB4rSTywzmMpL1SB/Bf+soLXvKSZDeJeVmwaJ0ISYVdj3okceHlL4+BIPTtvWOfY1lnZ68uyaC1JpxUasRx7t93xMqJilrdqeDvQezL2h74w0qLHnN8RIYAqgWRaD1j0zzPIJ5PD5VpwJpLMaZkXKmuuWvjk0FdJiBKnAXgH76L5kPg==,iv:xFSUJOZ6sH3E+1jXyPwrU5/6zXi3kszWsyKr0AXbkT0=,tag:/GKXKuInBp8dqmp7vesgSA==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFK0FPRytqSGthck5VMDkz
            ZThzZ1JuV1prbzRILzI4dW54VVVKTmZ1UTFNCldKKzRBZjIvM3ZhK1VwemZoaHU1
            R1BYblNXV3FQTDBhckxRT1hVZWlkeVUKLS0tIG1MN2wydU9oOW1GZXlIQklLcE8w
            TXNCNEFuTlp6WUxmTHhNazBubiszSG8KnkSaxPAAJGSWbMlLeTCuk9XTipDQTjk2
            wbDGBuFre+aLPz8gLFbiBoIKgeeAWctoP1aK01ysSbhv4FayOEwbcQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T19:04:26Z"
    mac: ENC[AES256_GCM,data:UIiWePGcKwZ2b5eaNVYckam/6qltjkVVb3bjrohnY+rxn1s2bYahHmFwqLuSH68fCyIwxuYCcAl9fWAo7Ro3H3ipqd598+mmwUpTZJHEe5fcXzk1stsW82ckxJP3gRUqK15sfoOgSDbGAUIuJGbskXu5UgqE+GMvR7G+lm8zY0A=,iv:kA9uDPMQZo4SPGnw+N11VZBpXTh40J2NnxwT7PWPEoQ=,tag:eb+NzugoSTRGcOvbmfgVbA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1