apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflared
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:ei1wT9AN1PiglNRuejEQZ33AwjWy5I6kFdZu3cY8wHTHLooysFvH1AAEie4dmfLEOH8eI5R3dslZPvtZvIPcEr0xws/AE1ewCPRGny/FZ0aZdEFuZVbvbYMfWyHyDGfuRFp3lmvE6IbpQcdAUKEbjlGMcKXsgslwY1KFLItp/Ydbpe+QAhuZFsLa3lt1HJF1YmkUr8u03LYX60+RDkJgZA42P4mARgIs3tGB9lqaePPg9NIG7pjx68LANU25FuXmomhE3C42AikhzHjDbaTe+eTPSj/pTjRSHSJLFvuykJqmb5qwEnEcugTZC2C81iVida0vO4b5VR8=,iv:UyXF1TfKNYbuAnolIFZHISmR05hZhnQB17Ivu3KiqB0=,tag:0jUOEFqP38Yoq259XJ/13g==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1QzlmWklRTkoyNUxLcTY5
            NjhNemVSWkdsVmp1RUVLb0t3M1Q1NmZCWDFFClUrY3h0WHF4eUdQTnZ3QjM2Z2xS
            Z2pUM1cybGs4VGhvVGRVd1NFTWVPMTAKLS0tIDdqMXc2ajl0RDFISjBFT2JIK1Y1
            dGpJQ0ZsVWVuZkRPMnhHd01oZ2FsSG8K4jsWdCHVjHEzKhUi62Zvkc2AwlLDyuTz
            jE7vXZfaJnGIHXMgGT/bR9bDpfU0OPvOnADDndpubeLmj+nJqyIwIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T20:17:40Z"
    mac: ENC[AES256_GCM,data:++KNilw01J906gyk9vYz0CkJ6mY6OZn81KUtuhf7yFsgn4FdhrcjICE09VXTQ2S7hA9nD6+J7bZcsZ9hy1hr75RKInjgeJADWU5OFpYkM3aJ+fIf7wnu5VkGiPqP5FijuNAKNbOC1FMX9Yvkc8s1ryYquWUxreJwqoQiuE0QiCc=,iv:X2sxAc4RLHPuc7klMapEXx7spz+5oshSRt3Tu3JKybQ=,tag:C5pQVLQ4Ww7DFcAQlsamnQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
