apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:puR7bpvF80tyjzH120aheNnMQCufr+e5vF2KYjbAjDnUryQnW3pYpP3btoeywyPiuZqIlnI=,iv:tpaDdllq8GxtcFJjl1ud+tDXMpsApVcq1HYtAJh/Z2M=,tag:ORyESytaqtPwsAgXEnrEjg==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEVVJsN25pLzNUbVY5RHZU
            N1I1bzREcEVUaW12YVJweFFlZDBHUVMreFFVCm9IRkMyK3pNZTN3eU1JbUpDR2lP
            TXVPMzU3UkZBT1JaOUdOK2piWWdadWsKLS0tIHFHdmtxa3dEN0tkYWhDYm8rM05y
            aGhWTTltbGpxSEpmZHlHcmI4OVU0U1UKMuZfwlfjYWq/92iCq++gnZOv/6PVGQ+J
            NwynlbAtkpygcqBa5FvHRqqiuebL8+hfllrIQpZZfIGsVc7oROclhw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T20:17:26Z"
    mac: ENC[AES256_GCM,data:6SZy7j7BxEWSq+TY1Gd4HtixboFyO9AZoSo2dUhcZQcNnWKPf0zYM2gzBNogB6MehQw/SLJVlkFm6L/SyNWNOoZOkR2gZs603iywiC9sSbY7F7vGAs0LlP7iQk3IEe3kRwNuIt9/vM6WMDwOBGjBPvtho31qVTcQaaE96gcXMRM=,iv:mtJIvD1po0BtJ+rMN5S57ZI8wclMightjVpkP1AJabU=,tag:9mZQTgEVNoWwHdlfPEK41w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
