apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
stringData:
    api-token: ENC[AES256_GCM,data:hySACO57zh2Vy4PVRZ8L5oPLlXASo3amZrGUTHRwZiJYYiG5MYgbL5NWeVlGnTzXuwGXb/8=,iv:0vdJs02uEzLwC4GHfSyYIqeH1/W35xTZVNSzkbiUoeA=,tag:7GHuOWcMJrvNl5NX7sHwqA==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2TDZwdXk4VUZ6VHM4Ly9t
            aTZvUkRzbU9YRk5aM1RRSDdONm9sSnJwTzA0CjBjcjFkR2QyQzc2N0pWTU9wUy9U
            Y2pGZWpCZXdnejlpbThpcjFlRVFXdzgKLS0tIFR2dEJoYlNtQiszMHlzbVlzeHJx
            elErNUtrTmFrR2Q2UkJkYVF6bEE1ZEEKtHo9cH+3bpa+qxEXM7P2fF5p3jT7xb4F
            Zd3SGet0EuUsYg+yXRSUQ4DP3Nna/hQJrgciOCuBvqVIYGGBd0SPww==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-12T12:37:13Z"
    mac: ENC[AES256_GCM,data:ioXlhrx3J/uGLkFVvgSl8XF34fMAkIAW0CEoQZR2GtxYS9yjgyU/xP+RyuDJL77nFfx9uvv/nXFvUlbMzCvFsnpTVdKYfw77JzuDYieI/Dt/JWke4ytgf2NjjD+gwXsF7NgPv1jzsZn5SVGD8bKBEh64SCQwzqZZkEgPmJcSAP8=,iv:xFgx7HJGkxPIyXKjnctF561OVBdImRCbxRMozBjKEC8=,tag:0jxnzsnuEqeNY+Nb7XHl8Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1