apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-token
    namespace: cloudflare
type: Opaque
stringData:
    tunnel-token: ENC[AES256_GCM,data:XvS4/MCC59/zmQDXlCrjXrpLS5ahZrnZvUDjqBmBSjZpptUOApHH4RikcSmKjBm4EqVpVoLAap1EhfN3LkHuV5w96AC4LyjYGgTeaZG6o8v9oULWADv8+OHHK5MBqDCME51m3TPSTGMC50nRrvbgM2TxhQWUUvuIely0Jv1YSKCdSCBKCrUH9Q9iwXvXFe6vjdesUxVBpI1GV/QyjG379SpPKr07XHKRicvnZMtLH5PMmEbmJiSuLg==,iv:EVmPwcLAmGwdFFxgXIzyO6OfLWaHfcoUGmipIkaErv0=,tag:+kpT5xevLwtuNjAjS1LAdw==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPclE5TkUvQktiR0srT3Fo
            aEI4Z1FJa01mR3R0ZU4zWWcyK2JEc3d0YzFZCmRPZW4yTkovYk9VN1NSeTUrOU1G
            YUp0dSs3Qy92VHlKS2E2RTdJazJwQ1kKLS0tIEprR3MybXBicFhNSnNldk14eDRw
            dU9ickxxNUdLaEgxZjdOMFc5UVJ0VUUKirYGsNKDcBcFSSn2l7Bk3AKCWkdlDa3c
            qQl+J1iPBgqpW/edl6FT9tkU06sbOpgSWOoKY+M8lb1Fp7i8C7TiPA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-13T18:47:38Z"
    mac: ENC[AES256_GCM,data:VLSa9SiCqFH40eC4RavJ606TjnLcgEDlrfWsdiMs3JQFqJ+rVMLappNMP98kjVGe08i0UmfdevA53Fz46VeXpBANTNnkotwchGmAhpeBI3mmSBZRAZ8V02BsO9Eu/cjbjAHjyc/s68j7dzvrVukwO1+DwVivsD2E9rSXn3uBrss=,iv:5tDjNRAePWnCVW+N5yJSnQLjUL3N5lhlPcAtM+20KJ0=,tag:orTcRpcJekGfKv2YmHB9pQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1