apiVersion: batch/v1
kind: Job
metadata:
  name: whoop-historical
  namespace: whoop
spec:
  template:
    spec:
      containers:
      - name: historical
        image: ghcr.io/mischavandenburg/whoop-scraper:v0.0.5
        command: ["/app/.venv/bin/whoop-scraper"]
        args: ["scrape", "--days", "629"]
        env:
        - name: WHOOP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              name: whoop-secrets
              key: client-id
        - name: WHOOP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: whoop-secrets
              key: client-secret
        - name: WHOOP_ACCESS_TOKEN
          valueFrom:
            secretKeyRef:
              name: whoop-secrets
              key: access-token
        - name: WHOOP_REFRESH_TOKEN
          valueFrom:
            secretKeyRef:
              name: whoop-secrets
              key: refresh-token
        - name: WHOOP_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: whoop-config
              key: WHOOP_DB_HOST
        - name: WHOOP_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: whoop-config
              key: WHOOP_DB_PORT
        - name: WHOOP_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: whoop-config
              key: WHOOP_DB_NAME
        - name: WHOOP_DB_USER
          valueFrom:
            configMapKeyRef:
              name: whoop-config
              key: WHOOP_DB_USER
        - name: WHOOP_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: whoop-cluster-app
              key: password
      restartPolicy: Never
  backoffLimit: 3