apiVersion: v1
kind: Secret
metadata:
    name: whoop-secrets
    namespace: whoop
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:45EaycZ4DWBXQN4VDnQt8BjTHbFmJtcwPbLPQIYRT6TBOPvm,iv:n7sobL9i9Rp040KHTv0u3ysUNtqm7+8+Rq5JR6QUqe8=,tag:rrbYrBMrCy2f29rhDIem+w==,type:str]
    client-secret: ENC[AES256_GCM,data:kZex1wu2Gejnjw4Bu9AdZo7BErBdBKCSDJHU2Ad75SiuY9AKdGdydazrDjUxzyNGFZKrGXChI3eUm93jY12NaA==,iv:ftKrVruxS34mfeyBlEM/ftLjTHTzhrWm3//g2a2AQ6M=,tag:27TQJUxlw2GDUNyzmhC92A==,type:str]
    access-token: ENC[AES256_GCM,data:kyiR3B5xPYGhFws2xp9un2wplEzfgFZ6X9XSYN6jBkhiUKIuBvQJOQKIYLbuiNI2KdO8AEOxQRYnTxgj+CZ6Z9pZI7o00TULFvULJAmw2pLNWrDlDp8i,iv:1HWwlgrD1Rnm1q/GilGC+cOqxDgcSKTZDKaFhOcGWfc=,tag:fygcU/DkTwjCI2SDfKUHog==,type:str]
    refresh-token: ENC[AES256_GCM,data:P56UjUKjmthnJHdZpw9NI1qSscdNZDkxSExUfkTWJz9icEBkpvkydU/ZOWYnQnsAmVUQvdH1nkpN8MYQKhNtQ9wy6rhhyGZCKPYR8khTDtHCK5ghiwjV,iv:1/KvQTRKwsbh/nS96PzB1g80Nb9esNzO2+S2V47AIgw=,tag:NT8pp3D06w350Emq5+as3Q==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRmUyekI4Z1Niam12ZTRI
            TG1rckptcTg2NXFkazdYUnh4NkNPY1RnUlhJCm9BUmdqbndkS2ovNVN0VGdhYzIz
            WHMvOU1iMHE1Q2l2QUlzcElvaG1KcWsKLS0tIENPTzRiUnc3NXVTd29pUHV0d0Ri
            eXR3TnR2eHNYUmhYU3ZTbWR4UCtFTmMK6cxROS1c+CSAU1olOmBw8XQkfQHSJHjL
            pvi00i7mSTwxVCOwCKSNAwcWFKByS1e9Se7XmiQ89alLT5YUyZNcbA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-16T18:21:33Z"
    mac: ENC[AES256_GCM,data:dDYjuMdL/T37VXKD7LBBn3ESgQMWE9EbFFnCXGhWXcjbw+FDbWD0urCXoFfw6TZXFwRtC9G7Wo0sRlhJ7GagklHFK+UcI+9Rd7nYsAbBZD7LBRG8CdI84j9rLwQ5g1q8HKMsjGiOzxa640qjJ2104IuvoCZUtr/WDwNsltnBIo8=,iv:7mVE8oaKYQVfYbJJa+XJlDqBzVJa9hSiKwhK2lkotPY=,tag:/AFEFKaecrgrmacXWgwiiw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
