apiVersion: v1
kind: Secret
metadata:
    name: whoop-secrets
    namespace: whoop
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:rUFSQENwS4mRZRlZlY514zxv/4eDlq7DerwsJ5x9RPg5sxo7,iv:T2JZzaVmo7k3ZAxUi9XNBhaetOOc4JjOijIkXOfoJn8=,tag:SuMMwtju6d6F8tkYL09orw==,type:str]
    client-secret: ENC[AES256_GCM,data:Cq4wFQFImcIpDpscuWso9+GMr7HSLLaiOD21q3IRnA1b5KtoBdpM0Pl7UFc67X6G7mn/EXm/wg1vt1pYrEnl1Q==,iv:AaGcQp7LHulrzPsc4MzdVYTrAbcIa0XDuFr+lo0rzwI=,tag:RxIJXOM+Nfn+hu/vNbQLjg==,type:str]
    access-token: ENC[AES256_GCM,data:9hgP9jsAT0SLOxnISZ0AUxqmSC9qZLTPHBSg4iiDg9TfO7LLFS/sydWMefUjqkpsmPfG9iE5e/fQrkvuuX9ntdR976gKazIODAZHP2iV/QmWlyfE3T1E,iv:y7p4sMlW0qFnt7hKY3MbP/iZqvCkyeQAwrpeDQ9lKq4=,tag:c0My3+5uituF+SNpS4q1ew==,type:str]
    refresh-token: ENC[AES256_GCM,data:fS4jMzSEEiFW7cpgBAdfoCFs+GeHHZ6GeHNMu3rqQkzrqrsL9bK9F6Hdoqsh73tJmVBz3AhEfNiYD4hNiiPcIi4K0CW4KYRLx8JfN3qJ0nJxPyto/cUL,iv:DMCibdL+dkIs3Tq2LgmcFpjsSChMPT1vRH7APtdSDlk=,tag:oVEcfxU3G69xmho+ITVlVQ==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNMVVvQjJIRVNKZnhrT2Ju
            czE5NzVkei9qN05JaTh2U1ZZRUkvRmJHMlQwClVwdmpNMDNDb01nblVPSlpiQlRO
            VEd1QTNjcHhZeUtZazlxdmJQSm1SWlEKLS0tIGM2b01WeFJMVGtpaDB1bWt1RTVU
            d3RWakFNYU5IbUZScjhWZWpQcTlVMnMKANTQrEmt28wpJt1PHHB6Mz1raLlAHSQP
            M8hXCJBp+cElRqs+92qOr0O3xS4O780ByWMlfzZv1yNIepi9BZVhNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T16:53:40Z"
    mac: ENC[AES256_GCM,data:HM7K7KRbrjUaiscBp1YhhyPQafQMwRch/aDH1W7NpP0Lr+RiGRrvEc9Zow2l4D4hgU9p/YWuGGYf9ZLYy2Ygv0tdxHkixsQMYp0cepbQPkmMGLLkxFXHVfBd2pKqUAJnrCdxBxQb3xV+t27wPH2mFbcCA+VnOr6IVJyaES3KtzU=,iv:nc7OKSPuu5gKa8PbZnh2fLMx+LZY5Akk1YL7CL1VnBw=,tag:NpId1mKqM2sqAt9A/EZsog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
