apiVersion: v1
kind: Secret
metadata:
    name: whoop-secrets
    namespace: whoop
type: Opaque
stringData:
    client-id: ENC[AES256_GCM,data:h57t2qOoUrMUOuWyQPD89GmRKHrApPezVqdQ3kq0osD/K4nC,iv:fdkQNDBRnckGEaKJWz6dYx4EepCdCMa71mh9v10YkW4=,tag:PyYk9WuzhhN/sV0P78mQig==,type:str]
    client-secret: ENC[AES256_GCM,data:kqhOVbvCHwJ4HAbuNJKn6aYMwVf4jDon7AfAY+zR2x+rxeMeY3+rwnoVVyuHnWoRkTOOQ1vDZ/24sX0opGI06w==,iv:EqqxbVrP2RPkQE8QkP7GEPpZ7dPyrJoJuyYYXFZkCWU=,tag:yMHEMNgNy0NN9p3YKd7Ljw==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYUR0MTArSnZYblZOZVNB
            eGFPTzZhWTltbnJNK0U1NXJSM1pkVjBFalNZCk43YUxHK3hXSnZTVmlMbktPOEhY
            VEhjUlU5VjdzQVoreHZsKzRxd3JublEKLS0tIHdKOXV5RitoU1VYeE9ibVNuUjVq
            YUNYK2hvU3F5dE9VZXdZNUI1anNuQUkKvNLM1xfPXLdangBWHK+/ysB+9myZaQt0
            QC5udH/zgLlVxxYOmvwIzSNqC+gyyoQE9IOlSKSNI4InmhpVWYL24Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-08T15:23:26Z"
    mac: ENC[AES256_GCM,data:olvGrtA9xWjiULjHYnKtCplmhI2Bx/beHcOqdbQKalSTk5nj+Kx6fa0gyObBwh7A0PoJqOQPtwaSmwJcXVjv2ytDBpqq1IMvXEbTDxpp1neHvI2OzAgMdAKrhILXzgbg2JAIP2d7OhT9pDTVsS54KzV+99AHuMOmqqpjYp6rGuQ=,iv:PxO/f9UtmquQ6d+0jbxeWS6mL6PJa5yjq4x6fG36R5I=,tag:NNlT2J2cAp2MR15WJSG2fg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
