apiVersion: v1
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm
stringData:
    MASTER_KEY: ENC[AES256_GCM,data:WgRTcnLB6yUNiB7AEtJPzFum187aGCUbaMiAYD5/0373vXr8DLg2E0RVwo3vP3L5,iv:YSJqYpOGSywVuan26Zc6W29Wd+iqWtqoo+nXnQl4New=,tag:D94tEjm9KlnIim2PocB1cw==,type:str]
    GEMINI_API_KEY: ENC[AES256_GCM,data:GNE9ozYUq6WH7eqd+FzIuPM2qp/6LQX8ZRbsh2IHsgCLsWnNfVLzYzrIDhavFOXoO88DkXU=,iv:KYq7UG2dpH3ZGhlQvr+b4lqxhqJkeZ9BdpmTjk7t52s=,tag:VK6ZJQq/0V24sT2fL2izvg==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByQkJOaENUWGEvUXJqcHBx
            UUNiUi9OcHExcFFMU3N4c08rNFpsY2hZSUVFClYySFFPK2lWc0JuVTE0bzJLdjlN
            cE9uazVFTk1NRWpSWmsvZVJPb1NaSEkKLS0tIDRCZEM2MDZMWTQzRnVFWnBDblhy
            QllpVS9FM1FTMUg4RXdvR2p1aGNxWWMKiDfUAerEMIjsDWWN73MCg1FWDPNEl4oH
            ia4hYsFnXQpreKuT8P4ipiWVeRrDnNYuKwKaEATUVQniFc0Q25OpSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T22:11:32Z"
    mac: ENC[AES256_GCM,data:hoJQMQ26nmhqQ1qj2V4w3zFqnqWWIpq/3UbAE1TQKPN/YjcCj+Wky006ceJ3QvyVeHnBzRC69ytFkfOFuFlYopYLXe81nm5vjQVc7yU4NjFMtluCl/2NcJ3+dC27lnhK2B2iR/R6wMRUpeiNTGRebuOX3gVRzo/yQvkBLNUD4oA=,iv:5qgUKUWiBdYx2FzOJXtsNalQi8/zLWIslrj7fZL8OjI=,tag:2n84nJKec+Ll4z/jRvCa0A==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
