apiVersion: v1
data:
    GEMINI_API_KEY: ENC[AES256_GCM,data:1gAbHnCCnqS8DCUXWM/ElEok19tXFuGfjGVqM6MtC/8OIfWM9/gNRMwnebyc5wjg5Wk2vg==,iv:9JQCb5rf4vYS6wpfCdX0nbdLll/BrzfmYVF44C9zPik=,tag:MCBe92BPMC2MoZKa0H8tvg==,type:str]
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NnhpZS9haUZSNHViSlNj
            cFpjdWsvSzAzaERjM1lHRHBPbW9vbHZSWG1jCmF4MExuaTRaYldUNkgyenJBMWZD
            b1hIUEprdjZHMEgrYjJBLzVuelpGN0EKLS0tIDJtKzZsbnlSVGVuYkZURWkrMTN4
            akJLM1ZsN05oNUQ2Y3VZY3dkUlVHTkkKc8wK/79MHxMg0tw3ECAygeNo/cTU6PJP
            AjtI+6zAiqEuZ0jhJNZyQG7vT1/yook6Boy0ws5imvhlN6p04SaWkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-09-10T21:02:48Z"
    mac: ENC[AES256_GCM,data:9o+l3GeOG+ntdyfBWmcI4Uc31O5seGByOJACW+4qR6lRXryxT1yJ5KZAGiZa53gXqXLl88m8BMBXMab3WHwkACDWpyKTCjTPq3ex9nqXRE5Hollq22PYBPKRvBpJyj8xteRAh1dDyosbVPkne5hAoyXZsJfZ/go6BL+qWh2gWdM=,iv:N8d8vcrxeVdJZqkX65nmPlepTPbH0LvxuJ+ETdHUAy4=,tag:PKlTyVqAnljr0pWqu7vqgQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
