apiVersion: v1
data:
    MASTER_KEY: gjeahslgh+adg+ahsdggaoh
    GEMINI_API_KEY: QUl6YVN5QzIzTmRqUk5xNDh2Y1FUYkNoRnZTRVFNQTRiVE1sUi1V
kind: Secret
metadata:
    name: litellm-secrets
    namespace: litellm