apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:GGus5UU=,iv:MosAvHEyNqzrhHUjAikz2FcK9ZxIIH0/DLZvR6JH0RI=,tag:oKdvqdUTQcrCMHiSTojYwg==,type:str]
    passwordKey: ENC[AES256_GCM,data:DNOTAGpc,iv:CP3yqn5JMI+eOwJ0I1js72z6osNfYCdTA34K4F6aPgQ=,tag:MdZ0LrwpgJcIsbXwecA/6A==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4ZmtJeGx6RDhOMXM2TlNn
            UVJKT3M3TlUvYStOYTRmcDVSWmtwZjBwd3hnCmROekRDMGhWZXlzc0JKS3R0R3Fm
            WTQxNFEybUkzek5ld0NUbDR4TzBxancKLS0tIGhxcUVIcDVQcVhscjFmUFc5MXdk
            bEpUd2ZLRHVQVlB5bzVKYkk3MklzR1kKO75AJeODqsRzAbjCzKhhJ3SHerTE9HNj
            1XJ92g4x7Mml0Ov8S30yd8xHCYeJ5fZA9ImpHUq2m3hwjmcVmz0CMw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-15T21:13:00Z"
    mac: ENC[AES256_GCM,data:M3JkQFbcrIGAGR2Qv0R6OACZMdLNKu61PB1A6+7BQRkvU+K5o4C0YSfFROdCHcvtq8RBc5rLZQrwhEqI5DTZZHuKiJJSYfT1thGc/ip3lZcfN434osKUXgDKrPidyY0e6km3sxvfOWBN2S8yIX5BOvpodiA9FDcIEKK4y/0xa+I=,iv:Nn1Cq6JbI68Zu+0cdTbJmYCL+QFQ9aKis+86C12FU0s=,tag:qETa8gMBDDsgnmWAXYgZ0w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1