apiVersion: v1
kind: Secret
metadata:
    name: grafana-secret
    namespace: monitoring
type: Opaque
stringData:
    admin-user: ENC[AES256_GCM,data:/d6DJKw=,iv:cBSue8wqKv0IvL9llYk7DjOhYdEaJFqhFUHEyaFTQqg=,tag:lIYVGGdMfoaNTvSbXC4jbQ==,type:str]
    passwordKey: ENC[AES256_GCM,data:LPwboKSh,iv:hY7tTQ5KAYiD/Gcz4xFRyr0GbT2754Bw2Ja4pD68wyQ=,tag:wWQKsNMAWkRrhHPm7tWH3w==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLK0ZSbWJJQzg0MFB2YVUv
            SkE0SkdIQUpVdzFENWZhbU4ydnNHeUN0dVJ3Ci9VelpQRzZ0OEhSVXNVQ2RHYVIy
            OUJxd3hqYk1LeEkyM01mS1p5TmM4UjQKLS0tIDdBUTBGcjV6a09aQW95ODNvejZw
            TmNIRncvbVFQL1M4YUprVUlObk5CYTgKLuhozUvV7nXWTGfIMmtG1v7GIfmN9fG3
            IHRPTeLgBRImxpx+pRsnqDechitmxmgvRWclECsu3aiuXLKyALC/Xg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T20:17:09Z"
    mac: ENC[AES256_GCM,data:/5xfnho1sfII+4cy5WbAzZuBFzXZThKoulb9hC0sF+NpYWkYpF/p9vvSBN8ctaq93jt8u5xUs+9JWEny4fqii40o6htXtNamtQj7TiZjeZRr4UOS00Ko12WcoERrP/FKNm6i68IHf0WJWbt9UeZRemZs1gggIzmjrNnoGWhEOvw=,iv:uhuhpmkGBFFY8pbAw6s9QDZsPbvbNiRY/KHuraEkHKs=,tag:cPh2BpuCkfrFtLpMB3zCYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
