apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: monitoring
type: Opaque
stringData:
    mail-password: ENC[AES256_GCM,data:mCVH3DwZfr7zHwTALyual+GzsQ==,iv:KgCl/cPA7WeUK9mZFLw9efR4zP7+UiLiY+WoXgzhWS4=,tag:kRRdhPzQ4g3BHhSJMBUXTQ==,type:str]
sops:
    age:
        - recipient: age1yksxhdl6f2epatdt88s9d9rmlte694q5xgd32sdez2h2uh9rxefqg4kyhx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBQ0RGTStGNHRuWGdYUkx6
            TkVBQmJZY2tlbTNsbk00Kys2MU5yQUkyNjJjCkJBbTNrZTRxWm1ZazRHVEJzc3JW
            dWt2RE84V3Z1cExRZXg0dXk4WkRwWEkKLS0tIHN6N3FBRzFzL0hWdE5JaHhwMXBG
            cGhrcGVSaWpaS3VtRUYrSEF1bUZzQ00K3girD901ZOfCcP+4POXLUJN1UaJOk2j+
            SaypeIsBcZoNItSY4VmCLjLkxQTAd4bAkAVb+Vje/FehrxDKF354NA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-27T20:53:31Z"
    mac: ENC[AES256_GCM,data:ungYrqqiXb9TS7bNyTbfoGSQlL5wuAmAUTBSuquLyANl4SHqg6RnBkzIV6lpcT7sjJIBj5EOG68C0GiqEcM09meacyJtm1PL5QClPZBdfjwywJeoqdEgdrLGlD3mjGSqeAKKn1Eaa6DqmPoO9QMZB/r0TzTZq8m40kMb7ef5gZE=,iv:bGlaY1FSGnClukG1ofgXj7VeM/BxNc6BIokNUfyLnHA=,tag:KWshiqEGJZFXCXGi32lT3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
