apiVersion: v1
kind: Secret
metadata:
    name: alertmanager-secret
    namespace: monitoring
type: Opaque
stringData:
    mail-password: ENC[AES256_GCM,data:AjJQqwmlvkAkLmkzAJDOvSikfg==,iv:bJilK3loxGO4ET90lmL02pQ0TMq5Ep/4SGXnT0XwtUk=,tag:lm4neMdj1OANSV9R5iEC/g==,type:str]
sops:
    age:
        - recipient: age1r3g27utsg0y3a6nf7l8cqrp9aen5k24anakd3gkc8nksxx7pcctqnuh55u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiSjUwWWNpS1FmenRYOWl0
            SkpDSnN0SVZUdVg0N0ZnMnRZTnVLWVFKOEVJCjVpY09RRXpaUzFCSkhBSnBvQ2h5
            UDZaVG56VmwySVcxZm1Hd2RrSEpacFkKLS0tIGZjVG1WZXdFS1k2aHlZRE5CTjcx
            Z2gwYllPeGVYOGtSVm5US1Qrd3ZCNVUK8bShT8jb6rd9ethFTrbjR1bjdu43hr/b
            Vhxxxicpwnw7g6MJ0nVlD01CYbia8OoH9bp8KikLS2evkbZS75Qb8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T20:17:16Z"
    mac: ENC[AES256_GCM,data:pSwlDolVfp66j0/pj3/WXkO6o6tonS6METmi2wUaIzYYWyI8x8Ofx5PPfEQvNKZRoYeoFj0sODfAsmQTvdUNBQ7L0cDqHGsQAAorUMUQVUTiO4V976G0d58jOKlJejisaGAaZXKNuohEvnrsRaVqXO9905iPXrF60NF7k7ku1IM=,iv:4O13rFOOK5HMzFkxAhxiuBVB+i8D/dxL3dnz92Wwbrc=,tag:z2M1FDEWDAXBMTUB/qGfog==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
